export const activityGraphSort: Array<{
  name: string;
  value: number;
}> = [
  { name: '4AM', value: 0 },
  { name: '5AM', value: 1 },
  { name: '6AM', value: 2 },
  { name: '7AM', value: 3 },
  { name: '8AM', value: 4 },
  { name: '9AM', value: 5 },
  { name: '10AM', value: 6 },
  { name: '11AM', value: 7 },
  { name: '12PM', value: 8 },
  { name: '1PM', value: 9 },
  { name: '2PM', value: 10 },
  { name: '3PM', value: 11 },
  { name: '4PM', value: 12 },
  { name: '5PM', value: 13 },
  { name: '6PM', value: 14 },
  { name: '7PM', value: 15 },
  { name: '8PM', value: 16 },
  { name: '9PM', value: 17 },
  { name: '10PM', value: 18 },
  { name: '11PM', value: 19 },
  { name: '12AM', value: 20 },
  { name: '1AM', value: 21 },
  { name: '2AM', value: 22 },
  { name: '3AM', value: 23 },
];

export const acrivityTime = [
  '4AM',
  '5AM',
  '6AM',
  '7AM',
  '8AM',
  '9AM',
  '10AM',
  '11AM',
  '12PM',
  '1PM',
  '2PM',
  '3PM',
  '4PM',
  '5PM',
  '6PM',
  '7PM',
  '8PM',
  '9PM',
  '10PM',
  '11PM',
  '12AM',
  '1AM',
  '2AM',
  '3AM',
];
