LOCATION_TYPES = ['ADDRESS', 'CITY', 'COUNTY', 'STATE', 'NATION']
BUSINESS_TYPES = ['BUSINESS', 'CATEGORY']
PERFORMANCE_DATA_TYPES = ['BRAND', 'CATEGORY', 'OVERALL', 'ADDRESS', 'CITY', 'STATE']
OWNERSHIP_DATA_TYPES = ['INFO', 'CONTACTS']
